//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class SisSchis
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SisSchis()
        {
            this.OperOnChiss = new HashSet<OperOnChiss>();
            this.OperOnChiss1 = new HashSet<OperOnChiss>();
            this.OperOnChiss2 = new HashSet<OperOnChiss>();
        }
    
        public int id { get; set; }
        public int Binary { get; set; }
        public int Quaternary { get; set; }
        public int Hexadecimal { get; set; }
        public int Octal { get; set; }
        public int Decimal { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OperOnChiss> OperOnChiss { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OperOnChiss> OperOnChiss1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OperOnChiss> OperOnChiss2 { get; set; }
    }
}
